import React from 'react';

export const INITIAL_STATE = {
    "1": {one: ['Color', ''],
    two: ['Plural Noun', ''],
    three: ['Adjective', ''],
    four: ['Celebrity', ''],
    five: ['Adjective', ''],
    six: ['Noun', ''],
    seven: ['Number', ''],
    eight: ['Number', ''],
    nine: ['Noun', ''],
    ten: ['Adjective', ''],
    eleven: ['Celebrity', ''],
    twelve: ['Celebrity', ''],
    thirteen: ['Adjective', ''],
    fourteen: ['Noun', ''],
    fifteen: ['Celebrity', ''],
    sixteen: ['Adjective', ''],
    title: 'An Odd Baseball Game',
    contentVisible: false,
    number: [1,'false']},

    "2": {one: ['Adjective', ''],
    two: ['Adjective', ''],
    three: ['Verb', ''],
    four: ['Celebrity', ''],
    five: ['Animal', ''],
    six: ['Adjective', ''],
    seven: ['Noun', ''],
    eight: ['Verb', ''],
    nine: ['Profession', ''],
    ten: ['Celebrity', ''],
    eleven: ['Thing', ''],
    twelve: ['Day', ''],
    thirteen: ['Activity', ''],
    fourteen: ['Vehicle', ''],
    fifteen: ['Name', ''],
    sixteen: ['Adjective', ''],
    title: "A Rainy Visit...",
    contentVisible: false,
    number: [2,'false']},

    "3": {one: ['Country', ''],
    two: ['Animal', ''],
    three: ['Adjective', ''],
    four: ['Adjective', ''],
    five: ['Noun', ''],
    six: ['Adjective', ''],
    seven: ['Adjective', ''],
    eight: ['Present Tense Verb', ''],
    nine: ['Number', ''],
    ten: ['Plural Noun', ''],
    eleven: ['Emotion', ''],
    twelve: ['Adverb', ''],
    thirteen: ['Name', ''],
    fourteen: ['Number', ''],
    fifteen: ['Celebrity', 'false'],
    sixteen: ['Adjective', 'false'],
    title: "La Grande Competition",
    contentVisible: false,
    number: [3,'false']},

    "4": {one: ['Boys Name', ''],
    two: ['Color', ''],
    three: ['Color', ''],
    four: ['Noun', ''],
    five: ['Sport', ''],
    six: ['Animal', ''],
    seven: ['Color', ''],
    eight: ['Past Tense Verb', ''],
    nine: ['Adjective', ''],
    ten: ['Adjective', ''],
    eleven: ['Thing', "false"],
    twelve: ['Day', "false"],
    thirteen: ['Activity', "false"],
    fourteen: ['Vehicle', "false"],
    fifteen: ['Name', "false"],
    sixteen: ['Adjective', "false"],
    title: "Perserverant Little Guy",
    contentVisible: false,
    number: [4,'false']},

    "5": {one: ['Day of Week', ''],
    two: ['Food', ''],
    three: ['Food', ''],
    four: ['Number', ''],
    five: ['Shape', ''],
    six: ['Adjective', ''],
    seven: ['Kitchen Utensil', ''],
    eight: ['Present Tense Verb', ''],
    nine: ['Noun', ''],
    ten: ['Noun', ''],
    eleven: ['Restaurant', ''],
    twelve: ['', "false"],
    thirteen: ['', "false"],
    fourteen: ['', "false"],
    fifteen: ['', "false"],
    sixteen: ['', "false"],
    title: "Dinnertime",
    contentVisible: false,
    number: [5,'false']},

    "6": {one: ['Day of the Week', ''],
    two: ['Noun', ''],
    three: ['Color', ''],
    four: ['Color', ''],
    five: ['Noun', ''],
    six: ['Adjective', ''],
    seven: ['Adjective', ''],
    eight: ['Adjective', ''],
    nine: ['Emotion', ''],
    ten: ['', 'false'],
    eleven: ['', "false"],
    twelve: ['', "false"],
    thirteen: ['', "false"],
    fourteen: ['', "false"],
    fifteen: ['', "false"],
    sixteen: ['', "false"],
    title: "Playground",
    contentVisible: false,
    number: [6, 'false']},

    // "6": {one: ['Boys Name', ''],
    // two: ['Color', ''],
    // three: ['Color', ''],
    // four: ['Noun', ''],
    // five: ['Sport', ''],
    // six: ['Animal', ''],
    // seven: ['Color', ''],
    // eight: ['Past Tense Verb', ''],
    // nine: ['Adjective', ''],
    // ten: ['Adjective', ''],
    // eleven: ['Thing', "false"],
    // twelve: ['Day', "false"],
    // thirteen: ['Activity', "false"],
    // fourteen: ['Vehicle', "false"],
    // fifteen: ['Name', "false"],
    // sixteen: ['Adjective', "false"],
    // title: "Perserverant Litte Guy",
    // contentVisible: false,},  
}